using ErpWeb.Authentication;
using ErpWeb.Components;
using ErpWeb.Core;
using ErpWeb.Core.Menus;
using ErpWeb.Model;
using ErpWeb.UI;
using ErpWeb.UI.Components.Common.DataGrid;
using ErpWeb.UI.Services;
using ErpWeb.UI.Services.Theme;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;
using Serilog;
using Microsoft.Extensions.DependencyInjection;
using Runners;

// Auto-generated by VS Code C# Dev Tools - Runner feature
// DI setup extracted from source Program.cs
// Source timestamp: 2026-08-10T05:00:37.166Z

// Set environment variables for appsettings.{Environment}.json loading
System.Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", RunnerSetup.Environment);
System.Environment.SetEnvironmentVariable("DOTNET_ENVIRONMENT", RunnerSetup.Environment);
System.Environment.SetEnvironmentVariable("environment", RunnerSetup.Environment);

Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateBootstrapLogger();

try
{
    var builder = WebApplication.CreateBuilder(args);

    builder.Host.UseSerilog((context, services, configuration) => configuration
        .ReadFrom.Configuration(context.Configuration)
        .ReadFrom.Services(services)
        .Enrich.FromLogContext()
        .Enrich.WithEnvironmentName()
        .Enrich.WithMachineName());

    builder.Services.AddRazorComponents()
        .AddInteractiveServerComponents();

    builder.Services.AddCascadingAuthenticationState();
    builder.Services.AddHttpContextAccessor();
    builder.Services.AddDevExpressBlazor(options =>
    {
        options.SizeMode = DevExpress.Blazor.SizeMode.Medium;
    });
    builder.Services.AddMvc();

    var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
        ?? throw new InvalidOperationException("Connection string 'DefaultConnection' is missing.");

    builder.Services.AddErpWebModel(connectionString);
    builder.Services.AddErpWebCore(builder.Configuration);
    builder.Services.AddScoped<ICookieSignInService, CookieSignInService>();
    builder.Services.AddScoped<CookiesService>();
    builder.Services.AddScoped<ThemeService>();
    builder.Services.AddScoped<PageNavigationGuard>();
    builder.Services.AddScoped<IGridLayoutStorage, LocalStorageGridLayoutStorage>();

    builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
        .AddCookie(options =>
        {
            options.Cookie.Name = "ErpWeb.Auth";
            options.Cookie.HttpOnly = true;
            options.Cookie.SecurePolicy = CookieSecurePolicy.SameAsRequest;
            options.Cookie.SameSite = SameSiteMode.Lax;
            options.LoginPath = "/login";
            options.LogoutPath = "/account/logout";
            options.AccessDeniedPath = "/unauthorized";
            options.ExpireTimeSpan = TimeSpan.FromHours(8);
            options.SlidingExpiration = true;
        });

    builder.Services.AddAuthorization(options =>
    {
        options.FallbackPolicy = new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .Build();
    });

// Apply custom runner DI configuration
RunnerSetup.ConfigureServices(builder.Services);

// Forward interface registrations to their concrete implementation types
if (RunnerSetup.AutoRegisterConcreteTypes) RegisterConcreteImplementationsAsSelf(builder.Services);

var serviceProvider = builder.Services.BuildServiceProvider();

static void RegisterConcreteImplementationsAsSelf(IServiceCollection services)
{
    var snapshot = services.ToList();
    var registered = new System.Collections.Generic.HashSet<Type>(
        snapshot
            .Where(d => d.ServiceType is { IsClass: true, IsAbstract: false } && !d.ServiceType.IsGenericTypeDefinition)
            .Select(d => d.ServiceType));

    // Count how many implementations each service type has. When an interface has more
    // than one implementation, GetRequiredService(interface) returns only the LAST one,
    // so forwarding a concrete type through it would resolve the wrong instance. In that
    // case we must pick the specific implementation by its runtime type instead.
    var serviceTypeCounts = new System.Collections.Generic.Dictionary<Type, int>();
    foreach (var d in snapshot)
    {
        if (d.ServiceType is null) continue;
        serviceTypeCounts.TryGetValue(d.ServiceType, out var existing);
        serviceTypeCounts[d.ServiceType] = existing + 1;
    }

    // Resolves the concrete implementation matching 'impl'. When the service type only has a
    // single implementation the fast path (GetRequiredService) is used; otherwise the correct
    // instance is selected from GetServices by matching its runtime type.
    static object ResolveConcrete(IServiceProvider sp, Type serviceType, Type impl, bool ambiguous)
    {
        if (ambiguous)
        {
            foreach (var candidate in sp.GetServices(serviceType))
            {
                if (candidate is not null && candidate.GetType() == impl) return candidate;
            }
        }
        return sp.GetRequiredService(serviceType);
    }

    // Phase 1: Direct registrations (ImplementationType / ImplementationInstance known)
    foreach (var d in snapshot)
    {
        if (d.ServiceType is null || d.ServiceType.IsGenericTypeDefinition) continue;
        if (!d.ServiceType.IsInterface && !d.ServiceType.IsAbstract) continue;
        var impl = d.ImplementationType ?? d.ImplementationInstance?.GetType();
        if (impl is null || impl.IsAbstract || impl.IsInterface || impl.IsGenericTypeDefinition) continue;
        if (impl == d.ServiceType || !registered.Add(impl)) continue;
        var serviceType = d.ServiceType;
        var concreteImpl = impl;
        var ambiguous = serviceTypeCounts.TryGetValue(serviceType, out var count) && count > 1;
        services.Add(new ServiceDescriptor(impl, sp => ResolveConcrete(sp, serviceType, concreteImpl, ambiguous), d.Lifetime));
    }

    // Phase 2: Factory registrations — resolve via a temp provider to discover runtime types
    var factories = snapshot.Where(d =>
        d.ServiceType is not null && !d.ServiceType.IsGenericTypeDefinition &&
        (d.ServiceType.IsInterface || d.ServiceType.IsAbstract) &&
        d.ImplementationType is null && d.ImplementationInstance is null).ToList();
    if (factories.Count > 0)
    {
        var tempSp = services.BuildServiceProvider();
        var scope = tempSp.CreateScope();
        try
        {
            foreach (var d in factories)
            {
                try
                {
                    var instance = scope.ServiceProvider.GetService(d.ServiceType!);
                    if (instance is null) continue;
                    var implType = instance.GetType();
                    if (implType.IsAbstract || implType == d.ServiceType || !registered.Add(implType)) continue;
                    var serviceType = d.ServiceType!;
                    var concreteImpl = implType;
                    var ambiguous = serviceTypeCounts.TryGetValue(serviceType, out var count) && count > 1;
                    services.Add(new ServiceDescriptor(implType, sp => ResolveConcrete(sp, serviceType, concreteImpl, ambiguous), d.Lifetime));
                }
                catch { /* Service not resolvable yet — skip */ }
            }
        }
        finally
        {
            // Some services (e.g. Azure Functions FunctionsTelemetryModule) only implement
            // IAsyncDisposable, so calling sync Dispose() throws. Prefer DisposeAsync and
            // swallow any disposal errors — the temp provider is only used for discovery.
            try
            {
                if (scope is IAsyncDisposable adScope) adScope.DisposeAsync().AsTask().GetAwaiter().GetResult();
                else scope.Dispose();
            }
            catch { /* ignore */ }
            try
            {
                if (tempSp is IAsyncDisposable adSp) adSp.DisposeAsync().AsTask().GetAwaiter().GetResult();
                else tempSp.Dispose();
            }
            catch { /* ignore */ }
        }
    }
}

// --- Runner Execution (auto-generated) ---
