<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Blazor" Version="26.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ErpWeb.UI\ErpWeb.UI.csproj" />
    <ProjectReference Include="..\ErpWeb.Core\ErpWeb.Core.csproj" />
    <ProjectReference Include="..\ErpWeb.Model\ErpWeb.Model.csproj" />
    <ProjectReference Include="..\ErpWeb.Library\ErpWeb.Library.csproj" />
    <ProjectReference Include="..\ErpWeb.Report\ErpWeb.Report.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Menus\menus.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
